#!/bin/sh

DEL="-------"
FIN="DONE"

print_start() {
	echo "$DEL ""$1"" $DEL"
}

print_end() {
	echo "$DEL ""$FIN ""$1"" $DEL"	
}

STR="STARTING FIRMWARE CONTAINER"
print_start "$STR"
cd /home/pi/git/GTernal/docker
sudo ./docker_run.sh
print_end "$STR"

STR="SETTING UP NETWORK HOST NAME"
print_start "$STR"
cd /home/pi/git/GTernal/setup
robot_id=$(python3 check_hostname.py ../config/mac_list.json)
sudo raspi-config nonint do_hostname $robot_id
print_end "$STR"

STR="REMOVING SETUP SCRIPT"
print_start "$STR"
rm /home/pi/setup_base_image
rm /home/pi/setup_from_base
rm /home/pi/get-docker.sh
print_end "$STR"

# STR="REBOOTING TO APPLY SETTINGS"
# print_start "$STR"
# sudo reboot